import Head from "next/head";
import NextLink from "next/link";

export default function MainHeader() {
  return (
    <Head>
      <title>Create Next App</title>
      {/* <meta name="description" content="Generated by create next app" /> */}
      <meta charSet={"utf-8"} />
      <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1, shrink-to-fit=no"
      />
      <meta name="description" content="" />
      <meta name="author" content=""></meta>
      <link rel="icon" href="/favicon.ico" />
      <link
        href="/assets/vendor/fontawesome-free/css/all.min.css"
        rel="stylesheet"
        type="text/css"
      />
      <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet"
      />
      <link href="/assets/css/sb-admin-2.min.css" rel="stylesheet"></link>
    </Head>
  );
}
